server:
  port: 5002

spring:
  application:
    name: airline-core-service

  datasource:
    url: jdbc:mysql://localhost:3306/msp_airlines_core_db
    username: root
    password: Pkul@4567

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
