server:
  port: 5008

spring:
  application:
    name: ancillary-service

  datasource:
    url: jdbc:mysql://localhost:3306/msp_airlines_ancillary_db
    username: root
    password: Pkul@4567

  jpa:
    hibernate:
      ddl-auto: update